// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const chrome = require('selenium-webdriver/chrome')
const assert = require('assert')

describe('Login', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    const browserName = process.env.E2E_BROWSER || process.env.SELENIUM_BROWSER || 'firefox'
    const builder = new Builder().forBrowser(browserName)

    if (browserName === 'chrome' && process.env.CI === 'true') {
      const options = new chrome.Options()
      options.addArguments('--headless=new', '--no-sandbox', '--disable-dev-shm-usage')
      builder.setChromeOptions(options)
    }

    driver = await builder.build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('Login', async function() {
    await driver.get("http://localhost:3000/")
    await driver.manage().window().setRect({ width: 1550, height: 830 })
    await driver.findElement(By.linkText("Ya tengo cuenta")).click()
    await driver.findElement(By.name("username")).click()
    await driver.findElement(By.name("username")).sendKeys("tester")
    await driver.findElement(By.name("password")).click()
    await driver.findElement(By.name("password")).sendKeys("Contraseña1")
    await driver.findElement(By.css(".text-zinc-900")).click()
    await driver.findElement(By.css(".gap-4 > .text-sm")).click()
  })
})
